kind = "DojoContract"
class_hash = "0x52861e4eceb9e0115958328b36f73498a7b156ed1c573c970c37aaefb1d4ffa"
original_class_hash = "0x52861e4eceb9e0115958328b36f73498a7b156ed1c573c970c37aaefb1d4ffa"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_examples_actions_actions.json"
reads = []
writes = []
computed = []
name = "dojo_examples::actions::actions"
