kind = "DojoContract"
class_hash = "0x3172c85c80f29a18c6635017ac0b60842ad27ae0d744ca5bbc8596defad94c"
original_class_hash = "0x3172c85c80f29a18c6635017ac0b60842ad27ae0d744ca5bbc8596defad94c"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_examples_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "dojo_examples::actions::actions"
