kind = "DojoContract"
class_hash = "0x5a25c37d48140ca0fb9536b7d8867e2a7bebf3fa896817d8b5f3dc01bbda40d"
original_class_hash = "0x5a25c37d48140ca0fb9536b7d8867e2a7bebf3fa896817d8b5f3dc01bbda40d"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_examples-actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "actions"
namespace = "dojo_examples"
manifest_name = "dojo_examples-actions"
artifact_name = "dojo_examples::actions::actions"
