kind = "DojoContract"
class_hash = "0x2bb3b0c6088e818191017dbbd1520c996ed40f7ad52298eb91c1890bf908cec"
original_class_hash = "0x2bb3b0c6088e818191017dbbd1520c996ed40f7ad52298eb91c1890bf908cec"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_examples_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "dojo_examples::actions::actions"
