kind = "DojoModel"
class_hash = "0x16141fdae16b43c612d705795e8993ebacd06edb4ec582041b15b6878d65de7"
original_class_hash = "0x16141fdae16b43c612d705795e8993ebacd06edb4ec582041b15b6878d65de7"
abi = "manifests/dev/base/abis/models/dojo_examples-PlayerConfig-3adad785.json"
tag = "dojo_examples-PlayerConfig"
manifest_name = "dojo_examples-PlayerConfig-3adad785"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "name"
type = "ByteArray"
key = false

[[members]]
name = "items"
type = "Array<PlayerItem>"
key = false

[[members]]
name = "favorite_item"
type = "Option<u32>"
key = false
