kind = "DojoModel"
class_hash = "0x794152290b915762781dc8cdd9e3c8ad9ae34f280f36c607fbe19e2d3c17d61"
original_class_hash = "0x794152290b915762781dc8cdd9e3c8ad9ae34f280f36c607fbe19e2d3c17d61"
abi = "manifests/dev/abis/base/models/dojo_examples_models_moves.json"
name = "dojo_examples::models::moves"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "remaining"
type = "u8"
key = false

[[members]]
name = "last_direction"
type = "Direction"
key = false
