kind = "DojoModel"
class_hash = "0x1cec286fb861c6e928c62ed270ddedd4d79691fdead0ed4faa74064d804f7ae"
name = "dojo_examples::models::position"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "vec"
type = "Vec2"
key = false
