[package]
description = "Katana RPC Implementation."
edition.workspace = true
license-file.workspace = true
name = "katana-rpc"
repository.workspace = true
version.workspace = true

[dependencies]
dojo-world = { workspace = true }
alloy = { git = "https://github.com/alloy-rs/alloy", rev = "7128c53"}
dojo-metrics.workspace = true
katana-core.workspace = true
katana-executor.workspace = true
katana-primitives.workspace = true
katana-provider.workspace = true
katana-rpc-api.workspace = true
katana-rpc-types-builder.workspace = true
katana-rpc-types.workspace = true
katana-tasks.workspace = true
tempfile = "3.8.1"
anyhow.workspace = true
flate2.workspace = true
futures.workspace = true
hex = { version = "0.4.3", default-features = false }
hyper = "0.14.20"
jsonrpsee = { workspace = true, features = [ "server" ] }
metrics.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
starknet.workspace = true
starknet_api.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower = { version = "0.4.13", features = [ "full" ] }
tower-http = { version = "0.4.1", features = [ "full" ] }
tracing.workspace = true
cainome.workspace = true

[dev-dependencies]
assert_matches = "1.5.0"
cairo-lang-starknet.workspace = true
cairo-lang-starknet-classes.workspace = true
dojo-test-utils.workspace = true
jsonrpsee = { workspace = true, features = [ "client" ] }
katana-rpc-api = { workspace = true, features = [ "client" ] }
katana-runner.workspace = true
url.workspace = true
