kind = "DojoContract"
class_hash = "0x14179d8db6fe166dff1a9746a39efb789a15643bc0c0afddce40d12caf4ecd6"
abi = "abis/base/contracts/actions.json"
reads = []
writes = []
computed = []
name = "dojo_examples::actions::actions"
